[package]
name = "miller_rabin"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = { version = "1.0.38" }
crypto-bigint = { version = "0.4.9" }
rand_core = { version = "0.6.4" }
hex = { version = "0.4.3" }